const mediaBase = "/coach-media";
const characterBase = `${mediaBase}/characters`;

export const coaches = [
  {slug:"mauste",name:"Mauste",tag:".mauste",mainCharacter:"jun",alts:["dragunov","xiaoyu","kunimitsu","miary-zo"],helpsAll:false,characters:"Jun Kazama (main). Voin valmentaa myös Dragunovia, Ling Xiaoyuta, Kunimitsua, Miary Zota ja Liliä.",experience:"Tekken 7 noin 225 h, Tekken 8 noin 1100 h. Ajoittain mukana online-viikkoturnauksissa.",specialty:"Jun Kazama -hahmospesialisti sekä harkitut riskit, setupit ja vastustajan lukeminen.",style:"Perusteista liikkeelle, jonka jälkeen harjoittelu rakennetaan pelaajalle luontevaksi. Replay-analyysiä ja oma-aloitteista opiskelua.",availability:"Vaihtelevasti; yleensä viikolla tai sunnuntaisin ennen klo 20. Aikataulu on joustava.",description:"Riskinottaja, joka nauttii odottamattomista ratkaisuista, setupeista ja vastustajan lukemisesta.",discord:"Mauste / .mauste"},
  {slug:"julumettu",name:"Julumettu",tag:"Joulumehu",mainCharacter:"nina",alts:["leo","dragunov","leroy"],helpsAll:false,characters:"Nina nykyisenä päähahmona; kokemusta myös Leosta, Dragunovista ja Leroysta.",experience:"Noin 2000 tuntia Tekkeniä ja kokemusta lähes koko rosterista.",specialty:"Mindgamet, pelaajan lukeminen ja uusien hahmojen opettelu.",style:"Perusasiat matalalla kynnyksellä, sitten syvemmälle sen mukaan mikä pelaajalle tuntuu luontevalta.",availability:"Ainakin yksi sessio viikossa; Discordissa voi kysyä matalalla kynnyksellä.",description:"Venkoilu, mindgamet ja tietotaidolla paikkaaminen mekaanisen optimoinnin sijaan.",discord:"Julumettu / Joulumehu"},
  {slug:"levis",name:"levis",tag:null,mainCharacter:"kazuya",alts:["claudio","king","hwoarang","devil-jin"],helpsAll:false,characters:"Kazuya (main). Claudio, King, Hwoarang, Devil Jin, Jin, Reina ja Nina secondaryina.",experience:"Pelannut Tekken 7:n julkaisusta asti, noin 4000 tuntia. Kaksi online-weekly-turnausvoittoa.",specialty:"Teknistä tarkkuutta vaativat taidot ja vastustajan virheistä rankaiseminen.",style:"Kysymyksiin vastaamista, mekaniikkojen avaamista ja Discord-valmennusta.",availability:"Melkein milloin vain.",description:"Tekninen ja rankaisemiseen nojaava pelityyli.",discord:"levis"},
  {slug:"zleepys",name:"Zleepys",tag:"Lumpo",mainCharacter:"alisa",alts:["devil-jin","heihachi","dragunov"],helpsAll:false,characters:"Alisa, Devil Jin, Heihachi ja Dragunov.",experience:"Back-to-back KGF LAN -tapahtuman voittaja.",specialty:"Vastustajan raivostuttaminen.",style:"1v1 hands-on -pelaamista, kysymyksiä ja replay-tilanteiden läpikäyntiä.",availability:"Arkisin klo 17–22, viikonloppuisin joustava.",description:"Tekninen taituri ja monen hahmon osaaja.",discord:"Zleepys / Lumpo"},
  {slug:"varathar",name:"Varathar",tag:null,mainCharacter:"law",alts:[],helpsAll:false,characters:"Law. Valmennuksessa myös Yoshimitsu ja muut tarvittaessa.",experience:"Tekken 3 lapsuudessa, Tekken 8 aktiivisesti vuodesta 2024. Taustaa kilpapelaamisen valmennuksesta Tikka Esportsissa.",specialty:"Kilpapelaamisen valmennus yleisesti ja yhdessä ongelmien selvittäminen.",style:"Suunnitelmallinen, mutta oppilas edellä. Oppimisen pitää pysyä hauskana.",availability:"Usein arkisin noin klo 18–20; viikonloput sovittavissa.",description:"Pitkän tien ja jatkuvan kehittymisen näkökulma.",discord:"Varathar"},
  {slug:"nixxoks",name:"Nixxoks",tag:"nhl_keissi",mainCharacter:"fahkumram",alts:["steve","heihachi","lee"],helpsAll:false,characters:"Fahkumram (main), lisäksi Steve, Heihachi ja Lee.",experience:"Noin vuosi Tekkeniä ja noin 250 tuntia peliaikaa.",specialty:"Puolustaminen, etäisyyden hallinta ja vastalyönnit.",style:"Mukautuu oppimistapaan; käytännön peliä ja teoriaa videoiden/diojen avulla.",availability:"Yleensä joka päivä klo 15:30 jälkeen.",description:"Rauhallinen alku, tempoa kohti loppua; etäisyyden hallintaa ja murskaavia vastalyöntejä.",discord:"nhl_keissi"},
  {slug:"dweben",name:"dweben",tag:"lolzben",mainCharacter:"yoshimitsu",alts:["kunimitsu","anna","miary-zo","zafina"],helpsAll:false,characters:"Yoshimitsu (main). Kunimitsu, Anna, Miary Zo, Zafina, Reina ja laaja muu rosteri.",experience:"Pelannut Tekkeniä vuodesta 1997 ja aktiivinen Suomi-Tekkenissä vuodesta 2021.",specialty:"Tyyli ennen substanssia ja nöyhtäiset setupit.",style:"Sparrailua, käytännön toistoja ja Rocky-montaasihenkeä.",availability:"Usein iltaisin klo 19 jälkeen, erityisesti ti–to.",description:"Tavoitteena voittaa sydämiä eikä vain eriä; omaan peliin sopivaa purkka-ja-jesari-ajattelua.",discord:"lolzben / dweben"},
  {slug:"ka-fu",name:"Ka-Fu",tag:"k_fu",mainCharacter:"hwoarang",alts:[],helpsAll:true,characters:"Hwoarang (main), pystyy auttamaan kaikkien hahmojen kanssa.",experience:"7 vuotta treenaamista ja turnauksia.",specialty:"Rauta mental ja whiff punishment.",style:"Kärsivällinen ja kannustava.",availability:"Hyvin joustava arkisin ja viikonloppuisin.",description:"Hot & cold.",discord:"Ka-Fu / k_fu"},
  {slug:"stupi",name:"Stupi",tag:null,mainCharacter:"armor-king",alts:["jack-8","claudio","zafina","king"],helpsAll:false,characters:"Armor King, Jack-8, Claudio, Zafina, King, Bryan ja Paul.",experience:"Pitkä Tekken-kokemus.",specialty:"Vastustajan ärsyttäminen ja pelityylin vaihtaminen.",style:"Rauhassa ja chillisti: ensin nykyinen osaaminen, sitten rakennetaan lisää.",availability:"Usein tavoitettavissa.",description:"Tilanteiden hakemista, vastustajan lukemista ja pelityylin muuttamista.",discord:"Stupi"},
  {slug:"pepsimayn",name:"Pepsimäyn",tag:null,mainCharacter:"bryan",alts:[],helpsAll:false,characters:"Bryan",experience:"Muutama vuosi Tekkeniä.",specialty:"Bryan ja taunt-tekniikat.",style:"Leppoisa.",availability:"Yleensä saatavilla.",description:"Bryan-spesialisti.",discord:"-Pepsimäyn-"},
  {slug:"roke",name:"Roke",tag:"Somppe",mainCharacter:"asuka",alts:["azucena","anna"],helpsAll:false,characters:"Asuka Kazama, Azucena Ortiz ja Anna Williams.",experience:"Noin 3000 tuntia Tekken 8:aa.",specialty:"Frame datan opiskelu.",style:"Kalvosulkeiset ja numeroista oppiminen.",availability:"Sovittavissa.",description:"Tekkenin ikuinen opiskelija, joka etsii vastauksia säntillisellä harjoittelulla.",discord:"Roke / Somppe"},
  {slug:"alika",name:"alika",tag:null,mainCharacter:"armor-king",alts:["feng"],helpsAll:true,characters:"Armor King ja Feng; voi valmentaa mitä tahansa hahmoa.",experience:"Yli 20 vuotta Tekkeniä, noin 10 vuotta tavoitteellisempaa online- ja turnauspelaamista.",specialty:"Laaja kokonaisosaaminen.",style:"Kompakti.",availability:"Noin kerran viikossa iltapäivisin.",description:"Monipuolinen.",discord:"alika"},
  {slug:"big-boss",name:"Big_Boss",tag:"bigbosso",mainCharacter:"azucena",alts:["paul","king","claudio","asuka"],helpsAll:false,characters:"Azucena, Paul, King, Claudio ja Asuka.",experience:"Yli 20 vuotta kilpapelaamista eri peleissä; Tekken-turnauskokemusta T7:stä eteenpäin sekä pitkä johtaja/valmentaja/opettajatausta.",specialty:"Adaptiivisuus, paine, ajoitus ja mental games.",style:"Aloitetaan vahvuuksien ja heikkouksien tunnistamisesta ja rakennetaan kehitys niiden ympärille.",availability:"Yleensä klo 18–23.",description:"Analyyttinen, adaptiivinen ja vahvasti kilpailuhenkinen.",discord:"Big_Boss / bigbosso"},
  {slug:"xeroh",name:"xeroh96",tag:null,mainCharacter:"lili",alts:["kunimitsu","bryan","dragunov"],helpsAll:false,characters:"Lili ja Kunimitsu päärooleissa; lisäksi Bryan ja Dragunov.",experience:"Pelannut Tekken 5:stä asti ja alkanut opetella peliä tavoitteellisesti Tekken 8:ssa.",specialty:"Lili-osaaminen ja käytännön matchupit.",style:"Etsitään pelaajalle oikea oppimistapa.",availability:"Melkein aina Discordista.",description:"Lili-spesialisti.",discord:"xeroh96"},
  {slug:"visatron",name:"Visatron",tag:null,mainCharacter:"jack-8",alts:[],helpsAll:true,characters:"Jack-8; voi valmentaa kaikkia hahmoja.",experience:"2 vuotta tavoitteellista pelaamista.",specialty:"Psykologia, mindgamet ja hauskanpito.",style:"Utelias ja produktiivinen.",availability:"Kolmivuorotyöstä huolimatta noin 1–2 sessiota viikossa.",description:"Saa paljon iloa pelaamisesta.",discord:"Visatron"},
  {slug:"velhonike",name:"Velhonike",tag:null,mainCharacter:"feng",alts:["shaheen"],helpsAll:true,characters:"Feng ja Shaheen; valmennettava päättää mitä haluaa pelata.",experience:"Kokeillut kaikkia Tekkeneitä Tekken 3:sta lähtien.",specialty:"Arjen ja harjoittelun yhdistäminen.",style:"Pelataan, katsotaan replayt ja mietitään mitä voisi tehdä paremmin.",availability:"Kerran viikossa.",description:"Rento kilpailu ja kehittyminen.",discord:"Velhonike"},
  {slug:"heddy",name:"Heddy",tag:"Heddyxo",mainCharacter:"feng",alts:["heihachi","reina"],helpsAll:true,characters:"Feng (main), Heihachi ja Reina; aloittelijalle voi valmentaa mitä tahansa hahmoa.",experience:"3–4 vuotta, yli 2000 tuntia, noin 20k peliä ja useita korkeatasoisia turnauksia online/offline.",specialty:"Jack of all trades.",style:"Kysymykset, tilanteiden ymmärtäminen, seuranta ja välitön palaute.",availability:"1–2 kertaa viikossa.",description:"Utelias, tekniikasta kiinnostunut, kilpailuhenkinen ja analyyttinen.",discord:"Heddy / Heddyxo"},
  {slug:"jarsos",name:"jarsos",tag:null,mainCharacter:"eddy",alts:["bryan","armor-king","jack-8"],helpsAll:false,characters:"Eddy & Bryan. Armor King ja Jack-8 menevät myös jotenkuten.",experience:"Kilpailullista Tekkeniä vuodesta 2013, TTT2:sta lähtien. Pelitunteja tuhansia, ellei kymmeniätuhansia.",specialty:"Enemmän selostaja kuin pelaaja — suu liikkuu monesti paremmin kuin kädet.",style:"Olennaiseen keskittyminen ja pienten askelten kautta suuriin maaleihin.",availability:"Viikolla normaalin 9–5 työajan ulkopuolella; viikonloput usein haastavia.",description:"Kovaa painamista ilman pelkoa.",discord:"jarsos"},
  {slug:"erkka",name:"erkka",tag:"erkkas",mainCharacter:"jin",alts:["kazuya","paul","yoshimitsu","armor-king"],helpsAll:true,characters:"Kazuya, Paul, Yoshimitsu, Armor King, Heihachi, Jin, King, Devil Jin, Bryan, Kuma, Panda, Claudio, Law, Jack-8, Fahkumram, Eddy, Lee, Feng, Clive ja Bob.",experience:"Tekken 7 ja Tekken 8 yhteensä yli 3400 tuntia.",specialty:"Korean Backdash ja useiden eri hahmojen osaaminen.",style:"Chill ja mukautuva: käydään Tekkenin perusteet läpi ja lähdetään siitä.",availability:"Hyvä; iltaisin yleisimmin paikalla.",description:"Fun enjoyer.",discord:"erkkas & erkka"},
  {slug:"munapoolo",name:"Munapoolo",tag:null,mainCharacter:"clive",alts:["victor"],helpsAll:false,characters:"Clive / Victor",experience:"Tuhansia tunteja pelejä ja turnauksia alla.",specialty:"Whiff punishit, hard readit ja väärin arvaaminen.",style:"Fiiliksen mukaan pelaaminen > tekninen osaaminen.",availability:"Discordin kautta saa kiinni, tavoitettavissa iltapäivällä ja illalla.",description:"Flashyt liikkeet ja pitkät combot > pikkutekken.",discord:"Munapoolo"},
  {slug:"zoomoo",name:"zoomoo",tag:null,mainCharacter:"paul",alts:[],helpsAll:false,characters:"Paul",experience:"2500 h Tekken 8 Paulia.",specialty:"Aina hyvällä asenteella vaikka tulee turpaan!",style:"Rento.",availability:"Iltaisin ja viikonloppuisin.",description:"Reaktiivinen fiilispelaaja, joka pystyy välillä yllättämään Suomen parhaimpiakin.",discord:"zoomoo"},
  {slug:"dankplank",name:"Dankplank",tag:null,mainCharacter:"steve",alts:["fahkumram","lee","paul","law"],helpsAll:false,characters:"Steve, Fahkumram, Bob, Lee, Paul, Law, Leroy, Heihachi sekä kokemusta Hwoarangista, Ling Xiaoyusta ja Yoshimitsusta.",experience:"Erilaisia taistelupelejä noin 15 vuoden ajalta. Tekken 7 ja 8 enemmän tavoitteellista kokemusta.",specialty:"Vastustajan lukeminen, combojen ja tilanteiden labraaminen sekä vihun höpläytys.",style:"Rentoa kikkailua ja tsekkailua.",availability:"Arkisin klo 16 jälkeen.",description:"All-around-pelaaja, jolle optimaaliset combot ja setupit ovat mieleen.",discord:"Dankplank"},
  {slug:"omnide",name:"OmnidE",tag:null,mainCharacter:"shaheen",alts:["leo","bob","feng"],helpsAll:false,characters:"Shaheen, Leo, Bob ja Feng.",experience:"Aloitti 2016, kilpaili vuodesta 2017 eteenpäin; hostannut showmatseja, turnauksia ja valmentanut muita.",specialty:"Mashaaminen.",style:"Tasapaino käytännön toistojen ja pienen teorisoinnin välillä.",availability:"Sovittavissa useampaan kertaan viikossa.",description:"Energinen paasaaja, joka haluaa saada pelaamiseen toistoja ja ymmärrystä.",discord:"OmnidE"}
].map((coach) => ({
  ...coach,
  poster: `${mediaBase}/${coach.slug}.jpg`,
  posterWide: `${mediaBase}/${coach.slug}-wide.jpg`,
  video: `${mediaBase}/${coach.slug}.mp4`,
  characterImage: coach.mainCharacter ? `${characterBase}/${coach.mainCharacter}.png` : null,
  altCharacterImages: (coach.alts || []).map((slug) => ({slug, url:`${characterBase}/${slug}-icon.png`})),
  allCharacterMosaic: ["kazuya","jun","xiaoyu","king","jin","nina","paul","yoshimitsu","hwoarang"].map(
    (slug) => ({ slug, url: `${characterBase}/${slug}-icon.png` })
  )
}));
