// Tekken Slam Suomi -osallistujat.
// Lisää uusi osallistuja kopioimalla yksi olio ja täydentämällä tiedot.
// Live-tiedot (isLive, streamTitle, viewerCount) korvataan myöhemmin Twitch API -integraatiolla.

export const players = [
  {
    id: "eryoces",
    name: "Eryoces",
    initials: "ER",
    twitchChannel: "eryoces",
    instagram: "erythewolf",
    tiktok: "Eryoces",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "jonssi",
    name: "Jönssi",
    initials: "JÖ",
    twitchChannel: "jonssi_",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "suikkari96",
    name: "Suikkari96",
    initials: "S9",
    twitchChannel: "suikkari96",
    instagram: "antti_sg96",
    tiktok: "suikkari96",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "pi4ch",
    name: "pi4ch",
    initials: "P4",
    twitchChannel: "pi4ch",
    instagram: "pi4ch",
    tiktok: "pi4ch",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "anmiina",
    name: "anmiina",
    initials: "AN",
    twitchChannel: "anmiina",
    instagram: "anmiina",
    tiktok: "anmiinaoriginal",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "huntari",
    name: "huntari",
    initials: "HU",
    twitchChannel: "huntari_",
    instagram: "anssikosola",
    youtube: "huntari",
    tiktok: "huntarifin",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "r1sbe",
    name: "r1sbe",
    initials: "R1",
    twitchChannel: "r1sbe",
    instagram: "risbekti",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "soca",
    name: "SoCa [FALX]",
    initials: "SC",
    twitchChannel: "socaw",
    instagram: "Arvo_j",
    tiktok: "socaws",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "iroaoyamada",
    name: "Iro Aoyamada [NIИ]",
    initials: "IA",
    twitchChannel: "iroaoyamada",
    youtube: "iroaoyamada",
    bluesky: "Aoyamadakun",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "the_katjaana",
    name: "The_katjaana [ɴᴏʀᴅ]",
    initials: "TK",
    twitchChannel: "the_katjaanaa",
    tiktok: "the_katjaana",
    youtube: "thekatjaana",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "sitra",
    name: "Sitra",
    initials: "SI",
    twitchChannel: "SitraGaming",
    youtube: "Sitra",
    tiktok: "sitragamingyt",
    instagram: "officialsitra_",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
  {
    id: "mr_randomizer",
    name: "Mr Randomizer [JoJo]",
    initials: "MR",
    twitchChannel: "mr_randomizer_",
    isLive: false,
    streamTitle: "",
    viewerCount: 0,
  },
];
